version: '3.8'

services:
  training-rocm:
    build:
      context: .
      dockerfile: Dockerfile.rocm
    volumes:
      - .:/app
      - ./models:/app/models
      - ./data:/app/data
    command: bash -c "python -m src.training.train_model"
    environment:
      - PYTHONPATH=/app
      - HIP_VISIBLE_DEVICES=0
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

  notebook-rocm:
    build:
      context: .
      dockerfile: Dockerfile.rocm
    volumes:
      - .:/app
      - ./models:/app/models
      - ./data:/app/data
    ports:
      - "8889:8888"
    command: bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    environment:
      - PYTHONPATH=/app
      - HIP_VISIBLE_DEVICES=0
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri 